### PR TITLE
Updated activation instruction for zsh color issue

### LINKED ISSUE #20: Not working for Ubuntu 20.04 - Alacritty
1. I downloaded and kept the ```dir_colors``` as ```~/.dir_colors```
2. Added ```test -r "~/.dir_colors" && eval $(dircolors ~/.dir_colors)``` command to the ```~/.bashrc``` and ```~/.zshrc``` both. After sourcing the ```ls``` command does not show NORD colors.

Please help.

### PR DESCRIPTION
**Pull request by szul**
This should resolve #20 and hopefully #17.

### CODE REVIEW

**Comment by brianrobt** [comment]
Can we get this merged?  This same applies for `fish`.

**Comment by szul** [comment]
No clue why it hasn't been reviewed or merged yet.

**Comment by brianrobt** [comment]
I'm using a completely different `.dir_colors` file now, which I actually like more: https://github.com/trapd00r/LS_COLORS

I have a patch ready for the `dircolors` util to add Fish support that I need to submit to GNU.

**Comment by arcticicestudio** [comment]
Hi @szul :wave:, thanks for your contribution :+1:

> No clue why it hasn't been reviewed or merged yet.

Even when this is “just“ a simple theme repository, the maintenance of the Nord could be a full time job. I'm a [single person][1] and there are currently [350+ issues and pull requests in all Nord repositories][2]. This does not include all the “support“ kanban boards, emails, GitHub and chat notifications and discussion threads so maintaining such a project next to a full time developer job is really time consuming.

Anyway, I guess there are also a few misunderstandings regarding the [`ls` command][11] the functionality of this theme for it. At first, it is important to know that **the `ls` command has absolute nothing to do with the shell**. In fact, function scope of most shells is actually very low and is almost only limited to the [shell builtins][2] and interpreter that is able to parse and understand the script code, e.g. `if` or `while` statements. However, it is important that **`ls` is not a shell builtin but a external executable!**
It should also be mentioned that each shell comes with its own builtins, even when most popular shells like [ZSH][4] and [Bash][5] are almost identical to each other.

Most of the user confusion arises because of the fact that there are **multiple implementation of `ls`**. The most common ones are

1. [GNU `ls`][6] (part of the Linux [core utils][12]), the one mainly targeted by this theme through the [`dircolors` command][7].
2. [BSD `ls`][8], the one distributed by operating systems like macOS.

The main difference between both is that they use different mechanisms to colorize their output. GNU `ls` reads the `LSCOLORS` environment variable that should contains ANSI like color definitions, e.g. `di=34:ln=35:so=32:pi=33:ow=30;43`. BSD `ls` on the other side checks and reads for the `LS_COLORS` environment variable, but expects a totally different format like `exfxcxdxbxegedabagacad`. Check out tools like the [LSCOLORS generator][9] to play around with both formats.

Maybe you wonder why this theme is called `dircolors` and not `lscolors`, and the answer is quite simply: it is targeted for [`dircolors`][7], a tool to simplify the composition and persistence of the value for the `LSCOLORS` environment variable. It reads a file (default: `~/.dir_colors`) that contains statements to define which colors to use for which file types and extensions. You can run `dircolors --print-database` to print the currently active definitions in your shell session environment.
So all the install command of this theme (`eval $(dircolors ~/.dir_colors)` placed in the initialization file of your shell) does is to execute the `dircolors` command in order to “convert“ the definitions from the file into the `LSCOLORS` specific format to be picked up by tools like GNU `ls` or other ones that respect this variable, e.g. [`tree`][10] or awesome (modern) tools like [`fd`][11].

In summary, that means that is **does not matter which shell is used but which implementation of `ls`**.
There is also a large box at the top of the [Nord dircolors documentation page about supported types][13] and information about GNU `ls` and `dircolors` in the [quick start section][14] of the repository README. An improvement might be to also include the large information box in the [theme installation documentation][15] to ensure that users are aware of it.

I hope this brings some light into this topic, but I totally feel that this complex, legacy history of shell tooling is kind of confusing :smile:
Modern tools like [`exa`][16], [`rg`][17] and [`fd`][11] exist to finally get things like this out of the world, but I guess the next 10+ generations will still have to deal with it until other tools replace the current default ones.

[1]: https://github.com/svengreb
[2]: https://github.com/issues?q=is%3Aopen+user%3Aarcticicestudio
[3]: https://en.wikipedia.org/wiki/Shell_builtin
[4]: http://zsh.sourceforge.net/Doc/Release/Shell-Builtin-Commands.html
[5]: https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html
[6]: https://github.com/coreutils/coreutils/blob/master/src/ls.c
[7]: https://www.gnu.org/software/coreutils/manual/html_node/dircolors-invocation.html
[8]: https://www.freebsd.org/cgi/man.cgi?ls
[9]: https://geoff.greer.fm/lscolors
[10]: https://en.wikipedia.org/wiki/Tree_(command)
[11]: https://github.com/sharkdp/fd
[12]: https://www.gnu.org/software/coreutils
[13]: https://www.nordtheme.com/docs/ports/dircolors/type-support
[14]: https://github.com/arcticicestudio/nord-dircolors#quick-start
[15]: https://www.nordtheme.com/docs/ports/dircolors/installation
[16]: https://github.com/ogham/exa
[17]: https://github.com/BurntSushi/ripgrep

**Pull request closed without merging**
