### PR TITLE
Add support for Alacritty

### PR DESCRIPTION
**Pull request by AidanGG**
Adds Alacritty support (for when not using tmux and using the alacritty terminfo files).

### CODE REVIEW

**Comment by AidanGG** [comment]
My text editor removed the trailing whitespace in the last commit. I can add it back via new lines for the Markdown line breaks if you'd like.

**Review by arcticicestudio — CHANGES_REQUESTED** [review]
Thanks for your contribution :+1: 

Based on [Alacritty's documentation about it's terminfo][acd] there is also another definition called `alacritty-direct` for 24-bit compatibility so it would be nice if you can add this one too. The missing `alacritty-256color` is fine since it has been removed in jwilm/alacritty#1491.

Also please revert the changes of the port project logos in the README back. I know some of them are broken, but there will be larger changes in the near feature anyway since they'll be moved to the [official Nord Docs][nd]

[nd]: https://github.com/arcticicestudio/nord-docs
[acd]: https://github.com/jwilm/alacritty/blob/master/INSTALL.md#terminfo

**Comment by murfalo** [comment]
Any updates on this?

**Review by svengreb — APPROVED** [review]

**Review by arcticicestudio — APPROVED** [review]
LGTM now, thanks again for your contribution 👍

**Pull request merged**
